export { default as Heading } from './Heading/Heading'
export { default as Subheading } from './Subheading/Subheading'
export { default as Footer } from './Footer/Footer'
export { default as DragNDrop } from './DragNDrop/DragNDrop'
export { default as Download } from './Download/Download'